<style>
#searchForm {
	margin-bottom: 20px;
}
#contentList th:hover{
	cursor: pointer;
}

#contentList td a {
	color: #333;
}

#contentList td a:hover {
	text-decoration: none;
	color: #333;
}

#paginatorNav {
	padding:0;
	margin:0;
}
</style>
<?php
if (!$this->isTotal) {
    $this->searchForm->addElement("button", "addContent", array("label" => "글쓰기", "class" => "btn"));
    $this->searchForm->getElement("addContent")->removeDecorator('Label');
}
echo $this->searchForm;
?>

<table id="contentList" class="table table-hover">
    <tr>
        <th class="title col-md-8" data-order-field="title">제목</th>
        <th class="writer col-md-2" data-order-field="writer">작성자</th>
        <th class="insertTime col-md-2" data-order-field="insertTime">작성일</th>
    </tr>
<?php
if ($this->paginator->getTotalItemCount() > 0) {
    foreach ($this->paginator->getCurrentItems() as $item) {
        echo "<tr>";
        echo "<td class=\"title\"><a href=\"/board_board/read-content/boardPk/{$this->boardPk}/contentPk/{$item['pk']}\">" . $item['title'] . "</a></td>";
        echo "<td class=\"title\">" . $item['writer'] . "</td>";
        echo "<td class=\"insertTime\">";
        $time = strtotime($item['insertTime']);
        echo strtotime(date("Y-m-d")) <= $time ? date("H:i", $time) : date("Y-m-d", $time);
        echo "</td>";
        echo "</tr>".PHP_EOL;
    }
} else {
    echo "<tr><td class=\"emptyRow\" colspan=3>게시글이 없습니다</td></tr>";
}
?>    
    

</table>
<div id="paginatorDiv" class="text-center">
<?php echo $this->paginator; ?>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$("#contentList th").each(function(){
		if ($(this).data("orderField") == $("#orderField").val()) {
			$(this).css("color", "#337ab7");
			$(this).append($("#order").val() == 'ASC' ? ' ▲' : ' ▼');
		}
	});
	$("#addContent").on("click", function(){
		window.location = "/board_board/edit-content/boardPk/" + "<?php echo $this->boardPk;?>";
	});

	$("#contentList th").on("click", function(){
		if ($(this).data("orderField") == $("#orderField").val()) {
			$("#order").val($("#order").val() == 'ASC' ? 'DESC' : 'ASC');
		} else {
			$("#orderField").val($(this).data("orderField"));
		}
		
		$("#searchForm").submit();
	});

	$("ul.pagination > li[class!=disabled][class!=active] > a").on("click", function(){
		$("#page").val($(this).data('page'));

		$("#searchForm").submit();
	});
});
</script>