<style>
#addForm {
	padding-bottom: 20px;
}
#addForm div.form-group:first-child {
    padding-left: 8px;
}
#addForm div.form-group label {
	margin-right: 10px;
}
#addForm input#name {
	width:80%;
}
#tableList th.isDisplay,
#tableList td.isDisplay {
	text-align: center;
}
</style>
<?php
echo $this->addForm;
?>
<table id="tableList"class="table table-hover">
    <tr>
        <th class="name col-xs-6">게시판명</th>
        <th class="ordered col-xs-1">정렬순서</th>
        <th class="isDisplay col-xs-1">표시유무</th>
        <th class="work col-xs-4">작업</th>
    </tr>
<?php
if (count($this->boards) > 0) {
    foreach ($this->boards as $row) {
        $boardList = $this->boardList;
        unset($boardList[$row->pk]);
        echo "<tr>";
        echo "<td class=\"name\">".$this->formText("name".$row->pk, $row->name, array("class" => "form-control input-sm name", "maxlength" => "16"))."</td>";
        echo "<td class=\"ordered\">".$this->formText("ordered".$row->pk, $row->ordered, array("class" => "form-control input-sm ordered"))."</td>";
        echo "<td class=\"isDisplay\">".$this->formCheckbox("isDisplay".$row->pk, $row->isDisplay, array(
        	"checked" => $row->isDisplay ? "checked" : ""
        ))."</td>";
        echo "<td class=\"work\">";
        echo $this->formButton("editBtn".$row->pk, "수정", array("class" => "btn btn-sm editBtn", "data-pk" => $row->pk));
        echo "&nbsp;" . $this->formSelect("boardList".$row->pk, "", array("class" => "form-control input-sm", "style" => "display:inline-block; width:auto;"), $boardList);
        echo "&nbsp;" . $this->formButton("moveBtn".$row->pk, "게시글 이동", array("class" => "btn btn-sm moveBtn", "data-pk" => $row->pk));
        echo "&nbsp;" . $this->formButton("deleteBtn".$row->pk, "삭제", array("class" => "btn btn-sm deleteBtn", "data-pk" => $row->pk));
        echo "</td>";
        echo "</tr>";
    }
} else {
    echo "<td colspan=4>생성된 게시판이 없습니다.</td>";
}
?>
</table>
<script>
$(document).ready(function(){
	var message = "<?php echo $this->message;?>";
	if (message) {
		alert(message);
	}

	function validate(parent) {
		var result = true;
		$.each(parent.find("input[type=text]"), function(){
			if ($(this).val().trim().length == 0) {
				alert("값을 입력해 주십시오");
				$(this).focus();
				result = false;
				
				return false;
			}

			if ($(this).hasClass("ordered") && ($(this).val().trim() < 1 || $(this).val().trim() > 255)) {
				alert("정렬순서 값은 1부터 255사이의 값으로 입력해주시기 바랍니다.");
				$(this).focus();
				result = false;
				
				return false;
			}
		});

		return result;
	}
	
	$("input[type=text].ordered").on("keydown", function(e){
		var keys = [8, 9, 16, 35, 36, 46];
		if (!((e.keyCode >= 48 && e.keyCode <= 57) || (e.keyCode >= 96 && e.keyCode <= 105) || keys.indexOf(e.keyCode) != -1)) {
			e.preventDefault();
		}
	});

	$("#addForm").on("submit", function(e){
		if (!validate($(this)) || !confirm("추가하시겠습니까?")){
		    e.preventDefault();
		}
	});

	$(".editBtn").on("click", function(){
		if (validate($(this).parents("tr")) && confirm("수정하시겠습니까?")) {
			var pk = $(this).data("pk");
	        $.ajax({
	        	url: "/board_config/board-edit",
	            type: "POST",
	            dataType: "json",
	            data: {
	                "pk" : pk,
	                "name" : $("#name" + pk).val(),
	                "ordered" : $("#ordered" + pk).val(),
	                "isDisplay" : $("#isDisplay" + pk).is(":checked") ? 1 : 0,
	            },
	            success: function(data) {
	                var message = data.result ? "수정되었습니다." : "수정 중 문제가 발생하였습니다.\n" + data.message;                               
	                  
	            	alert(message);
	            }
	        });
		}
	});

	$(".moveBtn").on("click", function(){
		var movePk = $("#boardList" + $(this).data("pk")).val();
		if (!movePk) {
			alert("이동할 게시판을 선택해주세요.");
			return false;
		}
		
		if (confirm("게시판의 게시물을 이동하시겠습니까?")) {
			var pk = $(this).data("pk");
			
	        $.ajax({
	        	url: "/board_config/board-move",
	            type: "POST",
	            dataType: "json",
	            data: {
                    "pk" : pk,
                    "movePk" : movePk,
	            },
	            success: function(data) {
	                var message = data.result ? data.message : "게시글 이동 중 문제가 발생하였습니다.\n" + data.message;                               
	                  
	            	alert(message);
	            }
	        });
		}
	});

	$(".deleteBtn").on("click", function(){
		if (confirm("게시판을 삭제하시겠습니까?") && confirm("게시판을 삭제하면 게시판의 게시물이 전부 삭제됩니다.\n게시판의 게시물은 '게시물 이동'을 통해 다른 게시판으로 옴길 수 있습니다.\n게시판을 삭제하시겠습니까?")) {
			var pk = $(this).data("pk");
	        $.ajax({
	        	url: "/board_config/board-delete",
	            type: "POST",
	            dataType: "json",
	            data: {
	                "pk" : pk,
	            },
	            success: function(data) {
	            	var message = data.result ? data.message : "게시판 삭제 중 문제가 발생하였습니다.\n" + data.message;                               
	            	alert(message);
	            	if (data.result) {
	            		window.location.href = window.location.href;
	            	}
	            }
	        });
		}
	});
	
});
</script>
