<?php echo $this->doctype() . "\n";?>
<html>
<head>
<?php echo $this->headTitle() . "\n"; ?>
<?php echo $this->headMeta() . "\n"; ?>
<?php
echo $this->headLink()
    ->prependStylesheet($this->baseUrl('/css/bootstrap-theme.min.css'), array('media' => 'all'))
    ->prependStylesheet($this->baseUrl('/css/bootstrap.min.css'), array('media' => 'all'))
    ->prependStylesheet($this->baseUrl('/css/general.css'), array('media' => 'all'))
    ->prependStylesheet($this->baseUrl('/css/navigation.css'), array('media' => 'all'));
echo "\n";

echo $this->headScript()
    ->prependFile($this->baseUrl('/js/bootstrap.min.js'))
    ->prependFile($this->baseUrl('/js/navigation.js'))
    ->prependFile($this->baseUrl('/js/jquery-3.2.1.min.js'));
echo "\n";
?>
</head>
<body>
<nav class="col-md-2" style="height: 100%; float:left; margin-top:40px;">
    <div class="profile text-center" style="width: 100%; height: 20%; border: 1px solid white;">
        <img src="<?php echo realpath(APPLICATION_PATH . "/datas/profile/profile.jpg")?>" alt="wanderer above the sea of fog" class="img-rounded" style="width:140px; height:140px;">
    </div>
    <?php
    echo $this->navigation()->menu()
        ->setIndent ("            ")
        ->setMaxDepth(3)
        ->setUlClass("navi")
        ->setPartial('partials/navigation.phtml');
    echo "\n";
    ?>
</nav>
<div class="col-md-10" style="height: 100%; border-left: 1px solid #ddd;">
    <div class="page-header">
        <h2><?php
        $active = $this->navigation()->findActive($this->navigation()->getContainer());
        if (!empty($active)) {
            $active = $active['page'];
            echo $active->getLabel();
        }
        ?>
        <small><?php echo $this->navigation()->breadcrumbs(); ?></small>
        </h2>
    </div>
    <div>
        <?php echo $this->layout()->content . "\n";?>
    </div>
</div>
<?php echo $this->inlineScript(); ?>
</body>
</html>